export const images = {
  authenticationBackgroundImageJpg: "@assets/images/authentication-background-image.jpg",
  authenticationBackgroundImage2xJpg: "@assets/images/authentication-background-image@2x.jpg",
  authenticationBackgroundImage3xJpg: "@assets/images/authentication-background-image@3x.jpg",
  couchsmileJpg: "@assets/images/couch_smile.jpg",
  couchsmile2xJpg: "@assets/images/couch_smile@2x.jpg",
  couchsmile3xJpg: "@assets/images/couch_smile@3x.jpg",
  dueDateBackgroundImageJpg: "@assets/images/due-date-background-image.jpg",
  dueDateBackgroundImage2xJpg: "@assets/images/due-date-background-image@2x.jpg",
  dueDateBackgroundImage3xJpg: "@assets/images/due-date-background-image@3x.jpg",
  firstIntroImagePng: "@assets/images/first-intro-image.png",
  firstIntroImage2xPng: "@assets/images/first-intro-image@2x.png",
  firstIntroImage3xPng: "@assets/images/first-intro-image@3x.png",
  keleyaLogoPng: "@assets/images/keleya-logo.png",
  notificationsBackgroundImageJpg: "@assets/images/notifications-background-image.jpg",
  notificationsBackgroundImage2xJpg: "@assets/images/notifications-background-image@2x.jpg",
  notificationsBackgroundImage3xJpg: "@assets/images/notifications-background-image@3x.jpg",
  workoutGoalBackgroundImageJpg: "@assets/images/workout-goal-background-image.jpg",
  workoutGoalBackgroundImage2xJpg: "@assets/images/workout-goal-background-image@2x.jpg",
  workoutGoalBackgroundImage3xJpg: "@assets/images/workout-goal-background-image@3x.jpg",
};
